### ISSUE TITLE
Unarchive QtSdkRepoChooser?

### ISSUE THREAD

**Issue by neelkarma** [JKSH/QtSdkRepoChooser#10]
Close this if I'm wrong, but I think qt just added the user-defined repositories menu back in the installer, so does that mean we can use QtSdkRepoChooser again?

![image](https://user-images.githubusercontent.com/59462098/124208777-a0a24d80-db2b-11eb-9270-45c0f4dce8fe.png)

**Comment by JKSH** [comment]
> I think qt just added the user-defined repositories menu back in the installer, so does that mean we can use QtSdkRepoChooser again?

That does not mean we can use QtSdkRepoChooser again, but there is something even better. The official installer supports mirrors now: https://wiki.qt.io/Online_Installer_4.x#Selecting_a_mirror_for_opensource
