### ISSUE TITLE
可选源列表里没有出现国内的那几个源

### ISSUE THREAD

**Issue by honeway** [JKSH/QtSdkRepoChooser#5]
看图
![](https://ws1.sinaimg.cn/large/890b5d95ly1ffl90i93ayj20ej058a9v.jpg)
https://ws1.sinaimg.cn/large/890b5d95ly1ffl90i93ayj20ej058a9v.jpg
想选高校的源，可选列表里没有

**Comment by JKSH** [comment]
The list of available mirrors is taken from http://download.qt.io/online/qtsdkrepository/windows_x86/root/qt/Updates.xml.mirrorlist

Different users will see a different selectable list of mirrors. I also don't see any mirrors from China.

I asked about this at the Qt Development mailing list. One user said that they can see 4 mirrors from China: http://lists.qt-project.org/pipermail/development/2017-May/029942.html
