### ISSUE TITLE
A qt project...

### ISSUE THREAD

**Issue by ehstoca** [JKSH/QtSdkRepoChooser#6]
Write a qt project that helps people with Qt installation issues is pure genius...

It's like when you have an internet connection issue and help desk of your ISP suggest you to visit their web site to find a solution...

GG WP

**Comment by JKSH** [comment]
> It's like when you have an internet connection issue and help desk of your ISP suggest you to visit their web site to find a solution

Without Qt installed, you can still download and run pre-compiled executables from https://github.com/JKSH/QtSdkRepoChooser/releases.

See instructions at http://htmlpreview.github.io/?https://github.com/JKSH/QtSdkRepoChooser/blob/master/doc/index.html.
