### ISSUE TITLE
im very sorry...

### ISSUE THREAD

**Issue by andreakarasho** [JKSH/QtSdkRepoChooser#8]
Hey, man im very sorry about it, but i 've not a way to send you a msg.

I've a little problem to run a qt gui in a std::thread, i followed your advices here:
https://stackoverflow.com/questions/22289423/how-to-avoid-qt-app-exec-blocking-main-thread/22290909#22290909

but i receve ever "WARNING: QApplication was not created in the main() thread."
and app crash...
Sorry man for this, i need help.

**Comment by JKSH** [comment]
You haven't provided enough info for anyone to understand and solve your problem. Please start by posting your code to https://forum.qt.io/ or https://stackoverflow.com/

**Comment by andreakarasho** [comment]
https://stackoverflow.com/questions/48284163/qt-gui-on-qthread/48285337#48285337

Already done
